import React from 'react';
import { Flex, Box, Text } from '@chakra-ui/react';

const HomePage = () => {
  return (
    <Flex direction="column" align="center" justify="center" p="5px 40px">
      <Flex wrap="wrap" justify="center">
        <Box w="45%" p="2">
          <Flex
            direction="column"
            align="center"
            borderRadius="20px"
            bg="rgba(19, 19, 48, 0.5)"
            backdropFilter="blur(10px)"
            p="20px"
            m="2"
            h="full"
          >
            <Text fontSize="xl" color="white" fontWeight="bold" marginBottom="2%">Context</Text>
            <Text color="white" textAlign="left">
              In today's digital age, the cryptocurrency market is burgeoning, yet it remains fragmented by a myriad of blockchain platforms, each with its unique set of addresses. This fragmentation poses significant challenges to users, from the complexity of managing multiple addresses to the heightened risk of transaction errors. Recognizing this critical pain point, Cryptoswiftapp proposes a revolutionary solution designed to unify the cryptocurrency experience across various blockchains, making transactions seamless and accessible to everyone.
            </Text>
          </Flex>
        </Box>
        <Box w="45%" p="2">
          <Flex
            direction="column"
            align="center"
            borderRadius="20px"
            bg="rgba(19, 19, 48, 0.5)"
            backdropFilter="blur(10px)"
            p="20px"
            m="2"
            h="full"
          >
            <Text fontSize="xl" color="white" fontWeight="bold" marginBottom="2%">Innovation Through AI</Text>
            <Text color="white" textAlign="left">
              At the heart of Cryptoswiftapp is our cutting-edge AI technology, which plays a pivotal role in enhancing the security and efficiency of cryptocurrency transactions. Our AI algorithms are designed to perform real-time analysis of transaction patterns, identifying potential errors or fraudulent activities before they occur. This proactive approach ensures that users can conduct transactions with confidence, knowing their assets are protected by the latest advancements in AI security.
              <br/><br/>
              Moreover, our AI system continuously learns and adapts to new threats, ensuring that Cryptoswiftapp stays at the forefront of cybersecurity. By leveraging AI, we not only streamline transactions but also pave the way for innovative features such as predictive market analysis, offering users insights into their cryptocurrency investments like never before.
            </Text>
          </Flex>
        </Box>

        <Box w="45%" p="2">
          <Flex
            direction="column"
            align="center"
            borderRadius="20px"
            bg="rgba(19, 19, 48, 0.5)"
            backdropFilter="blur(10px)"
            p="20px"
            m="2"
            h="full"
          >
            <Text fontSize="xl" color="white" fontWeight="bold" marginBottom="2%">Profit Potential</Text>
            <Text color="white" textAlign="left">
              Cryptoswiftapp is uniquely positioned to capitalize on the explosive growth of the cryptocurrency market. Our universal address management system addresses a critical market need, simplifying the cryptocurrency experience for millions of users worldwide. By reducing the barriers to entry, we anticipate a significant increase in cryptocurrency adoption, driving demand for our services.
              <br/><br/>
              Our revenue model is designed to capture value at multiple points in the transaction process, from premium features for advanced users to partnerships with blockchain platforms seeking to offer a more user-friendly experience. Additionally, the data generated by our AI algorithms presents opportunities for monetization through market insights and analytics services.
            </Text>
          </Flex>
        </Box>
        <Box w="45%" p="2">
          <Flex
            direction="column"
            align="center"
            borderRadius="20px"
            bg="rgba(19, 19, 48, 0.5)"
            backdropFilter="blur(10px)"
            p="20px"
            m="2"
            h="full"
          >
            <Text fontSize="xl" color="white" fontWeight="bold" marginBottom="2%">Why Invest in Cryptoswiftapp?</Text>
            <Text color="white" textAlign="left">
              <span style={{ fontWeight: 'bold' }}>Market Opportunity:</span> The cryptocurrency market is projected to continue its rapid growth, with increasing demand for user-friendly transaction solutions.
              <br />
              <span style={{ fontWeight: 'bold' }}>Innovative Technology:</span> Our unique integration of AI sets us apart, offering unparalleled security and market insights.
              <br />
              <span style={{ fontWeight: 'bold' }}>Experienced Team:</span> Our team consists of seasoned professionals with a proven track record in blockchain technology, AI, and cybersecurity.
              <br />
              <span style={{ fontWeight: 'bold' }}>Scalable Solution:</span> Cryptoswiftapp's platform is designed to scale, capable of supporting the growing number of users and transactions in the cryptocurrency market.
            </Text>
          </Flex>
        </Box>
      </Flex>
    </Flex>
  );
};

export default HomePage;
